
== Affine operation

The well-known affine function (ax + b) will allow us to unify the primitive  multiplication  and transposition operations into one single operation (with the aim of creating a group, not covered by this document).

=== Special Affine Operation

Multiplication and Transposition may be grouped into one special affine operation that operates on stem:[P(ZZ_n)].

When a group G acts on a set E then G acts in a natural way on P(E) := {A | A ⊆ E}, which is the set of all subsets of E.

Thus, when stem:[ZZ_12] is seen as the set of 12 pitch-classes, stem:[P(ZZ_12)] represents the set of possible scales restricted to an octave.

Operation name will be represented by  stem:[M_aT_k] (_M_~a~  for multiplication by _a_ and _T_~k~ for transposition by a step of _k_ semitones).

NOTE: Other representation is _T~k~M_ or _T~k~MI_ <<Rahn>>, but we prefer stem:[M_aT_k], echoing ax+b, which maps the precedence logic of internal operations (multiplication first, then addition).

====
[.text-center]
--
*Special Affine Operation*

stem:[M_aT_k  :  P(ZZ_n) xx NN xx ZZ -> P(ZZ_n)]

stem:[M_aT_k(A) := {\ (ax + k) mod n \ },  forall  x in A]

_Where *a* is coprime with n and *k* a step of transposition_

The coprime constraint under _a_ is important because it ensures that the operation gives a unique image to each elements of stem:[A sube ZZ_n], another way of saying stem:[A in P(ZZ_n)]

--
====

Examples when stem:[n = 12].{nbsp}{nbsp}stem:[ZZ_12 = {0, 1, ..., 11}], the coprimes with stem:[n] are {1, 5, 7, 11}

- stem:[M_1T_0("[0 4 7\]") -> "[0 4 7\]"] {nbsp} (neutral op)
- stem:[M_1T_5("[0 4 7\]") -> "[5 9 12\]"] so  stem:["[0 5 9\]"] Transposition of 5 semitones (T5)
- stem:[M_11T_0("[0 4 7\]") ->"[0 5 8\]"] {nbsp} Inversion, (C Maj -> Fm/5th)
- stem:[M_5T_5("[0 4 7\]") -> "[1 4 5\]"] {nbsp} Cycle fourths transformation followed by five semitone step transposition.

NOTE: stem:[M_aT_k] is also known as _TTO_ operators (for _Twelve Tone Operators_) and it's defined affine group (<<Morris>>, <<TOPOS>>). +
 +
For an in-depth study, with of a high level of mathematical conciseness, see <<Fripertinger>>


=== Special Affine Operation with complement

If we add the complementarity operation to the special affine function, we get the following operation: *stem:[c * (ax + k)]* that operates on stem:[P(ZZ_n)]. It is with this unified operation that we will work.

Operation name is {nbsp} stem:[C_cM_aT_k]

====
[.text-center]
--

*Extended Special Affine Operation*

stem:[ C_cM_aT_k : P(ZZ_n) xx {false, true} xx NN xx ZZ -> P(E) ]

stem:[C_cM_aT_k(A) := { ({\ (ax + k) mod n \ }  forall x in A \ \ \ \ \ \ \ \  if c = false), (ZZ_n\ \\ \ {\ (ax + k) mod n \ }  forall x in A \  if c = true) :}]
--

or, in condensed notation and if we use the special affine operation seen previously :
[.text-center]
--
stem:["[C\]"M_aT_k(A) := { (M_aT_k(A) \ \ \ \ \ \ \ \ if C " is not present"), (ZZ_n\ \\ \ M_aT_k(A)  if C " is present") :}]
--

====


Examples: stem:[ZZ_12 = {0, 1, ..., 11}] and the coprimes with n=12 are {1, 5, 7, 11}:

* stem:[M_1T_0("[0 4 7\]") -> "[0 4 7\]"] {nbsp} (neutral op)

* stem:[M_1T_1("[0 4 7\]") -> "[1 5 8\]"] {nbsp} (transposition of 1 semitone only)

* stem:[M_11T_0("[0 4 7\]") -> "[0 5 8\]"] {nbsp} (inversion)

* stem:[M_5T_0("[0 4 7\]") -> "[0 8 11\]"] {nbsp} (M5 only)

* stem:[CM_5T_4("[0 4 7\]") -> "[1 2 5 6 7 8 9 10 11\]"] {nbsp} (affine first then complement)

* stem:[M_11T_4("[0 2 4 5 7 9 11\]") -> "[0 2 4 5 7 9 11\]"] {nbsp} (Inversion then T4: C Major Diatonic -> C Major Diatonic)

* stem:[CM_1T_6("[0 2 4 5 7 9 11\]") -> "[0 2 4 7 9\]"] {nbsp} (T6 then Complement: C Major Diatonic -> C Major Pentatonic)

* stem:[CM_1T_0("[0 3 6 9\]") -> "[1 2 4 5 7 8 10 11\]"] {nbsp} (Complement only: Dim7 -> Dim scale)

// * *CM1-T0* {nbsp}:{nbsp} stem:[C_"true"M_1T_0("[0 2 4 5 7 9 11\]") -> "[1 3 6 8 10\]"] {nbsp} (complement only)

[TIP]
====

The number of versions of this operation is given by the formula: stem:[C^({0,1}) * M^(phi(n)) * T^n]

With stem:[n=12]{nbsp}, number of operations is:  stem:[2 xx 4 xx 12 = 96]
====


